### ISSUE TITLE
Updates to match reference implementation

### ISSUE THREAD

**Issue by wackazong** [blocklessnetwork/car-utils#13]
Hi there, I am trying to make a version of this library that produces the same CIDs as https://github.com/ipld/go-car and https://github.com/ipld/js-car. 

I see a problem in the way TSize is calculated. It lacks the addition of the metadata size as discussed here: https://discuss.ipfs.tech/t/how-to-decipher-root-node-content/11594/2

Other items I am adressing are missing block sizes in the pb-dag node, enable the choice of SHA2-256 as hash algorithm and adapt `MAX_SECTION_SIZE` to the reference implementations. 

Would you welcome a pull request?

**Comment by dmikey** [comment]
These are great, Please do forward a PR we would be very receptive to it!

**Comment by wackazong** [comment]
Created a PR.
